version: "3.9"

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta7
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    shm_size: "128mb" # update for your cameras based on calculation above
    cap_add:
      - CAP_PERFMON
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/config/config.yml
      - ./frigate-data/config:/config      
      - ./frigate-data/db:/db
      - ./frigate-data/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
